[package]
name = "crab-boy"
version = "0.1.0"
authors = ["phasma"]
edition = "2018"

[dependencies]
[dependencies.gtk]
version = "0.4.7"
package = "gtk4"

[dependencies.adw]
package = "libadwaita"
version = "0.1.1"
